<a href="https://colab.research.google.com/github/Prakritish-bhattacharya/NamasteAI/blob/Practical_Implementation/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

We use the Pandas library because it is the industry standard for data manipulation, analysis, and cleaning in Python API.

**Installation**

`pip install pandas`

After the Pandas have been installed in the system we need to import the library. The Pandas library can be imported using: 👇

In [1]:
import pandas as pd

**Note:** `pd` is just an alias for Pandas. It’s not required but using it makes the code shorter when calling methods or properties.

# Data Structures in Pandas

Pandas provides two data structures for manipulating data which are as follows:



1.   **Pandas Series:** A Pandas Series is a one-dimensional labeled array capable of holding data of any type. It can be created from Python Lists, NumPy arrays, dictionaries from external sources such as CSV files, Excel files and databases.

`pd.Series()` to convert the array into a Pandas Series.

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = np.array(['P','a','n','d','a','s'])
s = pd.Series(data)
print("Pandas series:")
print(s)

Pandas series:
0    P
1    a
2    n
3    d
4    a
5    s
dtype: object


2.   **Pandas DataFrame:** Pandas DataFrame is a two-dimentional data structure with row and columns. Collection of  multiple series call DataFrame.It is created by loading the datasets from existing storage which can be a SQL database, a CSV file or an Excel file.

In [4]:
import pandas as pd

df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [5]:
list = ['P','a','n','d','a','s']
df = pd.DataFrame(list)
print(df)

   0
0  P
1  a
2  n
3  d
4  a
5  s

# Let's more explore about Series

In [6]:
import pandas as pd
import numpy as np

In [7]:
labels = ['a','b','c']
my_list = [10,20,30] # list
arr = np.array([10,20,30]) # numpy array
d = {'a':10,'b':20,'c':30} # dictionary

In [8]:
#  create a series using list
series_list = pd.Series(my_list)
print(series_list)
print("-------------")
# create a series using numpy array
series_numpy_array = pd.Series(arr)
print(series_numpy_array)
print("-------------")
# create a series using dictionary
series_dictionary = pd.Series(d)
print(series_dictionary)

0    10
1    20
2    30
dtype: int64
-------------
0    10
1    20
2    30
dtype: int64
-------------
a    10
b    20
c    30
dtype: int64

In [9]:
# create series and implement index
# take list and index as labels
pd.Series(my_list, index = labels)

a    10
b    20
c    30
dtype: int64

In [10]:
# take numpy array and index as list
pd.Series(arr, index = my_list)

10    10
20    20
30    30
dtype: int64

In [11]:
# Series using dictionaries
pd.Series(d)

a    10
b    20
c    30
dtype: int64

# Let's more explore about DataFrames

In [12]:
#import required libraries
import pandas as pd
import numpy as np

#DataFrames
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
# crate DataFrame
df = pd.DataFrame(data)

In [13]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df = pd.DataFrame(data_list)
df

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

Create custom columns

In [14]:
#  create columns
columns = ["Name","Age","City","Salary"]
df_with_columns = pd.DataFrame(data_list, columns=columns) # pass columns as an Argument--- columns = columns
df_with_columns

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selection and Indexing of Columns**

In [15]:
'''In DataFrame You can't access columns using Indexes...
You need to access it using Column Name'''
df_with_columns["Name"]
df_with_columns[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

**Creating New Column**

In [16]:
df_with_columns["designation"] = ["Doctor","Eng","Teacher","Doctor"]
df_with_columns

    Name  Age      City  Salary designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000         Eng
2  Peter   29    Berlin   62000     Teacher
3  Linda   42    London   85000      Doctor

**Removing Columns**

In [17]:
# drop() → returns a modified copy
# axis=1 means column, while axis=0 means row.
drop_column = df_with_columns.drop("designation", axis = 1)
drop_column

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [18]:
# Selected column  not deleted from main DataFrame
df_with_columns

    Name  Age      City  Salary designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000         Eng
2  Peter   29    Berlin   62000     Teacher
3  Linda   42    London   85000      Doctor

In [19]:
# use inplace() ----> to show how selected column delete from main DataFrame
# inplace=True → modifies the existing DataFrame
df_with_columns.drop("designation", axis = 1, inplace = True)
df_with_columns

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [20]:
#  show updated DataFrame
df_with_columns

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Now we create multiple column. And delete these multiple columns

In [21]:
df_with_columns[["Designation","CTC"]] = [
    ["Doctor", "2.3"],
    ["Eng", "3.4"],
    ["Teacher", "2.1"],
    ["Advocate", "5.9"]
]
df_with_columns

    Name  Age      City  Salary Designation  CTC
0   John   28  New York   65000      Doctor  2.3
1   Anna   34     Paris   70000         Eng  3.4
2  Peter   29    Berlin   62000     Teacher  2.1
3  Linda   42    London   85000    Advocate  5.9

Delete Multiple Columns

In [22]:
delete_mul_column = df_with_columns.drop(['Designation','CTC'], axis=1, inplace=True)
delete_mul_column

In [23]:
df_with_columns

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Row Selection**

`.loc[]` is used to access rows or columns using their labels (index names).

`.loc[]` → Label-based selection 🏷️

In [24]:
df_with_columns.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [25]:
df_with_columns.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

`.iloc[]` is used to access rows or columns using their integer position (index).

`.iloc[]` → Position-based selection 🔢

In [26]:
df_with_columns.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

Select subset of a DataFrame

In [27]:
df_with_columns

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
# Select rows with index labels 0 and 1, then select only the 'City' and 'Salary' columns.
df_with_columns.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [29]:
# Select rows with index labels 0 and 1, then select only the 'Name' and 'Age' columns.
df_with_columns.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

# Conditional Selection

In [30]:
# Want to see those people whose age is above 30
df_with_columns[df_with_columns['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [31]:
# Want to see those people whose age is above 30 and their city must be paris
df_with_columns[
        (df_with_columns['Age'] > 30)
                    &
        (df_with_columns['City'] == 'Paris')
    ]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

# Missing Data

In [32]:
import numpy as np
import pandas as pd

In [33]:
# Create a DataFrame containing some missing (NaN) values.
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [34]:
# Count the number of missing (NaN) values in each column.
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [35]:
# Check whether each column contains at least one missing (NaN) value.
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

**Remember:** `dropna()` returns a new DataFrame; it does not modify df unless you use `inplace=True`.

In [36]:
# Remove every row that contains at least one missing (NaN) value.
# By default, dropna() works row-wise (axis=0).
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [37]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [38]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [39]:
# Replace all missing (NaN) values in the DataFrame with 0.
# By default, fillna() returns a new DataFrame and does not modify the original DataFrame.
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [40]:
# Create a dictionary that specifies a different replacement value
# for missing (NaN) values in each column.
values = {
    "A": 0,
    "B": 100,
    "C": 300,
    "D": 400
}

# Replace missing (NaN) values in each column with its corresponding
# value from the 'values' dictionary.
# A → NaN is replaced with 0
# B → NaN is replaced with 100
# C → NaN is replaced with 300
# D → NaN is replaced with 400
#
# fillna() returns a new DataFrame by default and does not modify 'df'.
df.fillna(values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [41]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

# Merging Joining and Concatination

**Merging**

In [42]:
import pandas as pd
import numpy as np

In [43]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [44]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [45]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

`inner` → Only matching records from both DataFrames.

In [46]:
# Merge the 'employees' and 'salaries' DataFrames using the common
# 'employee_id' column.
#
# how='inner' → Keeps only the rows where 'employee_id' exists
# in BOTH DataFrames.
#
# on='employee_id' → Specifies the column used to match records
# between the two DataFrames.
#
# pd.merge() returns a new DataFrame and does not modify the
# original 'employees' or 'salaries' DataFrames.
pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

`outer` → Keeps all records from both DataFrames.

In [47]:
# Merge the 'employees' and 'salaries' DataFrames using the common
# 'employee_id' column.
#
# on='employee_id' → Specifies the column used to match records
# between the two DataFrames.
#
# how='outer' → Keeps ALL records from BOTH DataFrames.
# If an employee_id exists in only one DataFrame, the missing
# values from the other DataFrame will be filled with NaN.
#
# pd.merge() returns a new DataFrame and does not modify the
# original 'employees' or 'salaries' DataFrames.
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

**Concatination of 2 DataFrames**

In [48]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [49]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [50]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [51]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [52]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**Joining 2 Data Frames**

In [53]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [54]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [55]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

# GroupBy

In [56]:
import numpy as np
import pandas as pd

In [58]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

**Group by Category and Calculate the sum of Sales**

In [63]:
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

**Group by Store and calculate the sum of Sales**

In [64]:
sto = df.groupby('Store')['Sales'].sum()
sto

Store
S1    720
S2    780
Name: Sales, dtype: int64

**Group by multiple columns
Group by Category and Store**

In [65]:
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

# Aggregation

In [66]:
df['Sales'].mean()

np.float64(187.5)

In [67]:
df['Sales'].median()

190.0

In [68]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64

In [69]:
df['Sales'].max()

300

In [70]:
df['Sales'].min()

100

In [71]:
df['Sales'].std()

66.06274074155351

In [75]:
df['Sales'].agg(['mean','median','max','min','count','std'])

mean      187.500000
median    190.000000
max       300.000000
min       100.000000
count       8.000000
std        66.062741
Name: Sales, dtype: float64

# Pivot Tables

In [3]:
import numpy as np
import pandas as pd

data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

# df['Month'] = df['Date'].dt.month_name()
# df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    914     73   John
1  2023-01-02       B   West    546     67   Mary
2  2023-01-03       C  North    467     99    Bob
3  2023-01-04       D  South    444     15  Alice
4  2023-01-05       A   East    822     47   John
5  2023-01-06       B   West    183     80   Mary
6  2023-01-07       C  North    879     19    Bob
7  2023-01-08       D  South    920     66  Alice
8  2023-01-09       A   East    184     88   John
9  2023-01-10       B   West    671     14   Mary
10 2023-01-11       C  North    917     14    Bob
11 2023-01-12       D  South    513     28  Alice
12 2023-01-13       A   East    173     33   John
13 2023-01-14       B   West    484     45   Mary
14 2023-01-15       C  North    198     16    Bob
15 2023-01-16       D  South    437     61  Alice
16 2023-01-17       A   East    804     86   John
17 2023-01-18       B   West    671     38   Mary
18 2023-01-19       C  North    682     72    Bob
19 2023-01-20       D  South    405     61  Alice

In [6]:
pd.pivot_table(df, values="Sales", index = "Region", columns = "Product", aggfunc = "median")

Product      A      B      C      D
Region
East     804.0    NaN    NaN    NaN
North      NaN    NaN  682.0    NaN
South      NaN    NaN    NaN  444.0
West       NaN  546.0    NaN    NaN

**Cross Tabs**

In [7]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# Operations

In [9]:
import numpy as np
import pandas as pd

df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

**shape**

In [12]:
df1.shape

(5, 3)

**columns**

In [13]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

**info()**

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

**describe()**

In [15]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [16]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

**DataFrames Applying Functions**

In [18]:
df1['D'] = df1["B"].apply(lambda x : x**2)
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500