<a href="https://colab.research.google.com/github/Prakritish-bhattacharya/NamasteAI/blob/Practical_Implementation/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

We use the Pandas library because it is the industry standard for data manipulation, analysis, and cleaning in Python API.

**Installation**

`pip install pandas`

After the Pandas have been installed in the system we need to import the library. The Pandas library can be imported using: 👇

In [1]:
import pandas as pd

**Note:** `pd` is just an alias for Pandas. It’s not required but using it makes the code shorter when calling methods or properties.

# Data Structures in Pandas

Pandas provides two data structures for manipulating data which are as follows:



1.   **Pandas Series:** A Pandas Series is a one-dimensional labeled array capable of holding data of any type. It can be created from Python Lists, NumPy arrays, dictionaries from external sources such as CSV files, Excel files and databases.

`pd.Series()` to convert the array into a Pandas Series.

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = np.array(['P','a','n','d','a','s'])
s = pd.Series(data)
print("Pandas series:")
print(s)

Pandas series:
0    P
1    a
2    n
3    d
4    a
5    s
dtype: object


2.   **Pandas DataFrame:** Pandas DataFrame is a two-dimentional data structure with row and columns. Collection of  multiple series call DataFrame.It is created by loading the datasets from existing storage which can be a SQL database, a CSV file or an Excel file.

In [4]:
import pandas as pd

df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [5]:
list = ['P','a','n','d','a','s']
df = pd.DataFrame(list)
print(df)

   0
0  P
1  a
2  n
3  d
4  a
5  s

# Let's more explore about Series

In [6]:
import pandas as pd
import numpy as np

In [7]:
labels = ['a','b','c']
my_list = [10,20,30] # list
arr = np.array([10,20,30]) # numpy array
d = {'a':10,'b':20,'c':30} # dictionary

In [8]:
#  create a series using list
series_list = pd.Series(my_list)
print(series_list)
print("-------------")
# create a series using numpy array
series_numpy_array = pd.Series(arr)
print(series_numpy_array)
print("-------------")
# create a series using dictionary
series_dictionary = pd.Series(d)
print(series_dictionary)

0    10
1    20
2    30
dtype: int64
-------------
0    10
1    20
2    30
dtype: int64
-------------
a    10
b    20
c    30
dtype: int64

In [9]:
# create series and implement index
# take list and index as labels
pd.Series(my_list, index = labels)

a    10
b    20
c    30
dtype: int64

In [10]:
# take numpy array and index as list
pd.Series(arr, index = my_list)

10    10
20    20
30    30
dtype: int64

In [11]:
# Series using dictionaries
pd.Series(d)

a    10
b    20
c    30
dtype: int64

# Let's more explore about DataFrames

In [13]:
#import required libraries
import pandas as pd
import numpy as np

#DataFrames
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
# crate DataFrame
df = pd.DataFrame(data)

In [18]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df = pd.DataFrame(data_list)
df

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

Create custom columns

In [19]:
#  create columns
columns = ["Name","Age","City","Salary"]
df_with_columns = pd.DataFrame(data_list, columns=columns) # pass columns as an Argument--- columns = columns
df_with_columns

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selection and Indexing of Columns**

In [25]:
'''In DataFrame You can't access columns using Indexes...
You need to access it using Column Name'''
df_with_columns["Name"]
df_with_columns[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London